### ISSUE TITLE
Sonos Connect does not display under Speakers & TV's but as a switch

### ISSUE THREAD

**Issue by rdouma** [nfarina/homebridge-sonos#84]
Any idea how this can be?

![2022-12-01_22-45-37](https://user-images.githubusercontent.com/1451271/205196001-f31ecbff-90dc-45ef-89e5-dfc44048b289.jpg)

**Comment by JohnathonMohr** [comment]
Hmm, I guess this is not very clear in the README, but showing as a switch is actually by design. Implementing it as a speaker is not straightforward, potentially not possible with how Homebridge works. There is an [alternative](https://github.com/nfarina/homebridge-sonos#alternative) mentioned in the README you can explore, with its own tradeoffs.

**Comment by rdouma** [comment]
Thanks for your answer! So the Sonos Connect doesn't "behave" like other Sonos speakers from Homebridge's perspective? The alternative you mention is the one where you can have a dimmer instead of an on/off switch right? That still wouldn't show it as a speaker. Anyway, it's not really a big deal, I am just trying to get Homekit as tidy as I can get it.

**Comment by JohnathonMohr** [comment]
Showing as a switch isn't unique to Connect - that's the design for all Sonos speakers. (It looks like you also have a Beam set up, showing as a switch as well, next to the Connect in the screenshot.) It's certainly not ideal, but it's what this plug-in can accomplish. And yes, the dimmer is the alternative - also not ideal, but can give some sort of volume control if that functionality is more desirable.

**Comment by rdouma** [comment]
Sure, I see the Beam as a switch but also as a speaker. Anyway, thanks for
explaining.
